version: '3.8'

services:
  api:
    build: ./app
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: vasc_teacher_portal
    volumes: 
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000