version: '3.8'

services:
  vasc_teacher_portal:
    build: 
      context: ../app
      dockerfile: Dockerfile.prod
    container_name: vasc_teacher_portal
    volumes: 
      - ../app/:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
            - .prod.env
