# Generated by Django 3.2.10 on 2022-02-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20220210_2222"),
        ("DataCollection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.course",
                    ),
                ),
            ],
        ),
    ]
