# Generated by Django 3.2.10 on 2022-02-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_staff"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(
                default="601 S. College Road, Wilmington, NC", max_length=256
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.CharField(
                default="University Of North Carolina at Wilmington", max_length=128
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Headset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac_address", models.CharField(max_length=12)),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.course",
                    ),
                ),
                (
                    "headset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="organizations.headset",
                    ),
                ),
                ("members", models.ManyToManyField(to="organizations.Student")),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="org_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.staff"
            ),
        ),
    ]
