# Generated by Django 3.2.10 on 2022-02-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_staff"),
        ("organizations", "0002_auto_20220203_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="org_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="staff_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.staff",
            ),
        ),
    ]
