# Generated by Django 3.2.10 on 2022-03-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20220210_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headset',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='headset',
            name='device_id',
            field=models.CharField(default='UNREGISTERED_HEADSET', max_length=32),
        ),
        migrations.AddField(
            model_name='headset',
            name='device_nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='headset',
            name='device_reference_id',
            field=models.CharField(default='01234567890123', max_length=14),
        ),
        migrations.AlterField(
            model_name='headset',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.organization'),
        ),
    ]
