# Generated by Django 3.2.10 on 2022-03-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20220318_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headset',
            name='device_reference_id',
        ),
    ]
